name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'  # Adjust to your Julia version

      - name: Cache Julia packages
        uses: actions/cache@v4
        with:
          path: ~/.julia
          key: ${{ runner.os }}-julia-${{ hashFiles('.github/workflows/test.yml') }}
          restore-keys: |
            ${{ runner.os }}-julia-

      - name: Install dependencies
        run: |
          julia -e 'import Pkg; Pkg.add(["SatelliteDynamics", "SatelliteToolbox", "SatelliteToolboxTransformations", "SatelliteToolboxGeomagneticField", "Plots"])'

      - name: Run tests
        run: julia test/runtests.jl
